# Generated by Django 4.0.5 on 2022-06-27 13:16

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Classifier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Введите отраслевой классификатор документа', max_length=255, verbose_name='Отраслевой классификатор документа')),
            ],
            options={
                'verbose_name': 'Отраслевой классификатор документа',
                'verbose_name_plural': 'Отраслевые классификаторы документов',
            },
        ),
        migrations.CreateModel(
            name='Format',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Введите формат документа', max_length=255, verbose_name='Формат документа')),
            ],
            options={
                'verbose_name': 'Формат документа',
                'verbose_name_plural': 'Форматы документов',
            },
        ),
        migrations.CreateModel(
            name='Language',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Введите язык', max_length=255, verbose_name='Язык документа')),
            ],
            options={
                'verbose_name': 'Язык документа',
                'verbose_name_plural': 'Языки документов',
            },
        ),
        migrations.CreateModel(
            name='Technology',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Введите технологию', max_length=255, verbose_name='Технология документа')),
            ],
            options={
                'verbose_name': 'Технология документа',
                'verbose_name_plural': 'Технологии документов',
            },
        ),
        migrations.CreateModel(
            name='Type',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Введите тип документа', max_length=255, verbose_name='Тип документа')),
            ],
            options={
                'verbose_name': 'Тип документа',
                'verbose_name_plural': 'Типы документов',
            },
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, help_text='Уникальный идентификатор', primary_key=True, serialize=False)),
                ('id_doc', models.CharField(help_text='Введите код документа', max_length=255, verbose_name='Код документа')),
                ('date_add', models.DateField(auto_now=True)),
                ('short_name', models.CharField(help_text='Введите коротное название документа', max_length=255, verbose_name='Короткое название документа')),
                ('autor', models.CharField(blank=True, help_text='Введите автора документа', max_length=255, verbose_name='Автор документа')),
                ('isbn', models.CharField(blank=True, help_text='13 символов <a href="https://www.isbn-international.org/content/what-isbn" target="_blank">ISBN номер</a>', max_length=13, unique=True, verbose_name='ISBN документа')),
                ('bbk', models.CharField(blank=True, help_text='Введите ББК документа', max_length=255, verbose_name='ББК документа')),
                ('udk', models.CharField(blank=True, help_text='Введите УДК документа', max_length=255, verbose_name='УДК документа')),
                ('main_doc', models.BooleanField(default=0, help_text='(Да/Нет)', verbose_name='Основной документа')),
                ('rel_date_doc', models.DateField(help_text='Введите дату выхода документа', verbose_name='Дата выхода документа')),
                ('original_source', models.CharField(blank=True, help_text='Введите первоисточник документа', max_length=1000, verbose_name='Первоисточник документа')),
                ('short_desc', models.CharField(blank=True, help_text='Введите краткое описание документа', max_length=255, verbose_name='Краткое описание документа')),
                ('file_doc', models.FileField(blank=True, help_text='Выберите документ', upload_to='docs/', verbose_name='Документ')),
                ('classifier_doc', models.ForeignKey(help_text='Выберите отраслевой классификатор документа', on_delete=django.db.models.deletion.PROTECT, to='home.classifier', verbose_name='Отраслевой классификатор документа')),
                ('format_doc', models.ForeignKey(help_text='Выберите формат документа', on_delete=django.db.models.deletion.PROTECT, to='home.format', verbose_name='Формат документа')),
                ('language', models.ForeignKey(help_text='Выберите язык документа', on_delete=django.db.models.deletion.PROTECT, to='home.language', verbose_name='Язык документа')),
                ('technology_doc', models.ForeignKey(help_text='Выберите технологию документа', on_delete=django.db.models.deletion.PROTECT, to='home.technology', verbose_name='Технология документа')),
                ('type_doc', models.ForeignKey(help_text='Выберите тип документа', on_delete=django.db.models.deletion.PROTECT, to='home.type', verbose_name='Тип документа')),
            ],
            options={
                'verbose_name': 'Документ',
                'verbose_name_plural': 'Документы',
                'ordering': ['short_name'],
            },
        ),
    ]
